// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cchvnudjrsoxqhibghbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjaHZudWRqcnNveHFoaWJnaGJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDkxMTYsImV4cCI6MjA3NDE4NTExNn0.3kXpWOsi7wbMFTVzYKoVGNbfPhTk6rKSa5acOsgZcAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});